resources:
  - ../../base
  - namespace.yaml

namespace: dev-fastapi

patches:
  - path: patches/app-deployment-patch.yaml

configMapGenerator:
  - name: app-envs
    envs:
      - envs/app.env.example

secretGenerator:
  - name: app-secrets
    files:
      - secrets/api_key.secret.example
