apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment
  labels:
    app: go-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: go-webapp-container
          image: quay.io/falrayes/go-argocd-workshop:dev-e7dc0879003909360426a64b73c8169a0d8d50a8
