name: Go Deployment CI

on:
  push:
    branches:
      - master

env:
  DOCKER_APP_REPO: app-argocd-workshop
  CI_COMMIT_MESSAGE: "[ci-auto-commit] Continuous Integration: Manifests generated and updated."
  CI_COMMIT_AUTHOR: GitHub Workflows

jobs:

  build:
    name: Build the container image.
    if: "!startsWith(github.event.head_commit.message, '[ci-auto-commit] ') && github.event.head_commit.author.username != 'GitHub Workflows'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          context: ./webapp
          file: webapp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_APP_REPO }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_APP_REPO }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  update-manifests:
    name: Update the kubernetes manifests
    if: "!startsWith(github.event.head_commit.message, '[ci-auto-commit] ') && github.event.head_commit.author.username != 'GitHub Workflows'"
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_WORKFLOWS_TOKEN }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin

      # This step is very important for the CD part of the pipeline.
      # The generated manifests in the step(Generate and update manifests) are for any user to take a quick look on the manifests built by Kustomize and are being applied.
      # However ArgoCD is pointing towards the particular overlay with a kustomize.yaml file to generate and apply the manifests immediately.
      # Put simply it is the overlay that will be the source of the apply (kubectl apply -k overlay/dev) NOT (kubectl apply -f gitops/kustomized_output/manifests.yaml)
      - name: Update the patch with the approperiate tag name for ArgoCD
        run: |
          sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_APP_REPO }}:.*|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_APP_REPO }}:${{ github.sha }}|' gitops/overlays/dev/patches/app-deployment-patch.yaml

      - name: Generate and update manifests
        run: |
          kustomize build gitops/overlays/dev > gitops/kustomized_output/manifests.yaml
          sed -i '1s/^/# git commit: ${{ github.sha }}\n/' gitops/kustomized_output/manifests.yaml

      - name: Git setup, add, commit, and push
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add gitops/kustomized_output/manifests.yaml 
          git add gitops/overlays/dev/patches/app-deployment-patch.yaml
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
